name: "Nix Flake"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: "Check `nix develop` shell"
        run: nix develop --check
      - name: "Check `nix develop` shell can run command"
        run: nix develop --command echo
      - run: nix build
      - run: nix flake check
      - name: "Run all Haskell tests in the `nix develop` shell"
        run: |
          nix develop --command cabal update
          nix develop --command cabal test
      - name: "Run all PureScript tests in the `nix develop` shell"
        run: nix develop --command spago test
